spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 111111

const:
  jwt:
    key: 'MapleChenX'
    expire: 72
    limit:
      base: 10
      upgrade: 300
      frequency: 30
